/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThemeImport } from './routes/theme'
import { Route as LogoutImport } from './routes/logout'
import { Route as IndexImport } from './routes/index'
import { Route as ThemeTypographyImport } from './routes/theme/typography'
import { Route as ThemeThemesImport } from './routes/theme/themes'
import { Route as ThemeSidebarImport } from './routes/theme/sidebar'
import { Route as ThemeOthersImport } from './routes/theme/others'
import { Route as RenegociatedHomeImport } from './routes/renegociated/home'
import { Route as RenegociatedDashboardImport } from './routes/renegociated/dashboard'
import { Route as RenegociatedAdminUsersImport } from './routes/renegociated/admin/users'
import { Route as RenegociatedAdminRolesImport } from './routes/renegociated/admin/roles'

// Create/Update Routes

const ThemeRoute = ThemeImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThemeTypographyRoute = ThemeTypographyImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => ThemeRoute,
} as any)

const ThemeThemesRoute = ThemeThemesImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => ThemeRoute,
} as any)

const ThemeSidebarRoute = ThemeSidebarImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => ThemeRoute,
} as any)

const ThemeOthersRoute = ThemeOthersImport.update({
  id: '/others',
  path: '/others',
  getParentRoute: () => ThemeRoute,
} as any)

const RenegociatedHomeRoute = RenegociatedHomeImport.update({
  id: '/renegociated/home',
  path: '/renegociated/home',
  getParentRoute: () => rootRoute,
} as any)

const RenegociatedDashboardRoute = RenegociatedDashboardImport.update({
  id: '/renegociated/dashboard',
  path: '/renegociated/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const RenegociatedAdminUsersRoute = RenegociatedAdminUsersImport.update({
  id: '/renegociated/admin/users',
  path: '/renegociated/admin/users',
  getParentRoute: () => rootRoute,
} as any)

const RenegociatedAdminRolesRoute = RenegociatedAdminRolesImport.update({
  id: '/renegociated/admin/roles',
  path: '/renegociated/admin/roles',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeImport
      parentRoute: typeof rootRoute
    }
    '/renegociated/dashboard': {
      id: '/renegociated/dashboard'
      path: '/renegociated/dashboard'
      fullPath: '/renegociated/dashboard'
      preLoaderRoute: typeof RenegociatedDashboardImport
      parentRoute: typeof rootRoute
    }
    '/renegociated/home': {
      id: '/renegociated/home'
      path: '/renegociated/home'
      fullPath: '/renegociated/home'
      preLoaderRoute: typeof RenegociatedHomeImport
      parentRoute: typeof rootRoute
    }
    '/theme/others': {
      id: '/theme/others'
      path: '/others'
      fullPath: '/theme/others'
      preLoaderRoute: typeof ThemeOthersImport
      parentRoute: typeof ThemeImport
    }
    '/theme/sidebar': {
      id: '/theme/sidebar'
      path: '/sidebar'
      fullPath: '/theme/sidebar'
      preLoaderRoute: typeof ThemeSidebarImport
      parentRoute: typeof ThemeImport
    }
    '/theme/themes': {
      id: '/theme/themes'
      path: '/themes'
      fullPath: '/theme/themes'
      preLoaderRoute: typeof ThemeThemesImport
      parentRoute: typeof ThemeImport
    }
    '/theme/typography': {
      id: '/theme/typography'
      path: '/typography'
      fullPath: '/theme/typography'
      preLoaderRoute: typeof ThemeTypographyImport
      parentRoute: typeof ThemeImport
    }
    '/renegociated/admin/roles': {
      id: '/renegociated/admin/roles'
      path: '/renegociated/admin/roles'
      fullPath: '/renegociated/admin/roles'
      preLoaderRoute: typeof RenegociatedAdminRolesImport
      parentRoute: typeof rootRoute
    }
    '/renegociated/admin/users': {
      id: '/renegociated/admin/users'
      path: '/renegociated/admin/users'
      fullPath: '/renegociated/admin/users'
      preLoaderRoute: typeof RenegociatedAdminUsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ThemeRouteChildren {
  ThemeOthersRoute: typeof ThemeOthersRoute
  ThemeSidebarRoute: typeof ThemeSidebarRoute
  ThemeThemesRoute: typeof ThemeThemesRoute
  ThemeTypographyRoute: typeof ThemeTypographyRoute
}

const ThemeRouteChildren: ThemeRouteChildren = {
  ThemeOthersRoute: ThemeOthersRoute,
  ThemeSidebarRoute: ThemeSidebarRoute,
  ThemeThemesRoute: ThemeThemesRoute,
  ThemeTypographyRoute: ThemeTypographyRoute,
}

const ThemeRouteWithChildren = ThemeRoute._addFileChildren(ThemeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRouteWithChildren
  '/renegociated/dashboard': typeof RenegociatedDashboardRoute
  '/renegociated/home': typeof RenegociatedHomeRoute
  '/theme/others': typeof ThemeOthersRoute
  '/theme/sidebar': typeof ThemeSidebarRoute
  '/theme/themes': typeof ThemeThemesRoute
  '/theme/typography': typeof ThemeTypographyRoute
  '/renegociated/admin/roles': typeof RenegociatedAdminRolesRoute
  '/renegociated/admin/users': typeof RenegociatedAdminUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRouteWithChildren
  '/renegociated/dashboard': typeof RenegociatedDashboardRoute
  '/renegociated/home': typeof RenegociatedHomeRoute
  '/theme/others': typeof ThemeOthersRoute
  '/theme/sidebar': typeof ThemeSidebarRoute
  '/theme/themes': typeof ThemeThemesRoute
  '/theme/typography': typeof ThemeTypographyRoute
  '/renegociated/admin/roles': typeof RenegociatedAdminRolesRoute
  '/renegociated/admin/users': typeof RenegociatedAdminUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRouteWithChildren
  '/renegociated/dashboard': typeof RenegociatedDashboardRoute
  '/renegociated/home': typeof RenegociatedHomeRoute
  '/theme/others': typeof ThemeOthersRoute
  '/theme/sidebar': typeof ThemeSidebarRoute
  '/theme/themes': typeof ThemeThemesRoute
  '/theme/typography': typeof ThemeTypographyRoute
  '/renegociated/admin/roles': typeof RenegociatedAdminRolesRoute
  '/renegociated/admin/users': typeof RenegociatedAdminUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/theme'
    | '/renegociated/dashboard'
    | '/renegociated/home'
    | '/theme/others'
    | '/theme/sidebar'
    | '/theme/themes'
    | '/theme/typography'
    | '/renegociated/admin/roles'
    | '/renegociated/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/theme'
    | '/renegociated/dashboard'
    | '/renegociated/home'
    | '/theme/others'
    | '/theme/sidebar'
    | '/theme/themes'
    | '/theme/typography'
    | '/renegociated/admin/roles'
    | '/renegociated/admin/users'
  id:
    | '__root__'
    | '/'
    | '/logout'
    | '/theme'
    | '/renegociated/dashboard'
    | '/renegociated/home'
    | '/theme/others'
    | '/theme/sidebar'
    | '/theme/themes'
    | '/theme/typography'
    | '/renegociated/admin/roles'
    | '/renegociated/admin/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoutRoute: typeof LogoutRoute
  ThemeRoute: typeof ThemeRouteWithChildren
  RenegociatedDashboardRoute: typeof RenegociatedDashboardRoute
  RenegociatedHomeRoute: typeof RenegociatedHomeRoute
  RenegociatedAdminRolesRoute: typeof RenegociatedAdminRolesRoute
  RenegociatedAdminUsersRoute: typeof RenegociatedAdminUsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoutRoute: LogoutRoute,
  ThemeRoute: ThemeRouteWithChildren,
  RenegociatedDashboardRoute: RenegociatedDashboardRoute,
  RenegociatedHomeRoute: RenegociatedHomeRoute,
  RenegociatedAdminRolesRoute: RenegociatedAdminRolesRoute,
  RenegociatedAdminUsersRoute: RenegociatedAdminUsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logout",
        "/theme",
        "/renegociated/dashboard",
        "/renegociated/home",
        "/renegociated/admin/roles",
        "/renegociated/admin/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/theme": {
      "filePath": "theme.tsx",
      "children": [
        "/theme/others",
        "/theme/sidebar",
        "/theme/themes",
        "/theme/typography"
      ]
    },
    "/renegociated/dashboard": {
      "filePath": "renegociated/dashboard.tsx"
    },
    "/renegociated/home": {
      "filePath": "renegociated/home.tsx"
    },
    "/theme/others": {
      "filePath": "theme/others.tsx",
      "parent": "/theme"
    },
    "/theme/sidebar": {
      "filePath": "theme/sidebar.tsx",
      "parent": "/theme"
    },
    "/theme/themes": {
      "filePath": "theme/themes.tsx",
      "parent": "/theme"
    },
    "/theme/typography": {
      "filePath": "theme/typography.tsx",
      "parent": "/theme"
    },
    "/renegociated/admin/roles": {
      "filePath": "renegociated/admin/roles.tsx"
    },
    "/renegociated/admin/users": {
      "filePath": "renegociated/admin/users.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
